version: "3.4"

services:
  master:
    build: master/
    environment:
      - secondary_a_path=http://secondary_a:5001
      - FLASK_DEBUG=1
      - secondary_b_path=http://secondary_b:5001
    command: python ./master.py
    ports:
      - "5000:5000"
    networks:
      - replicated-log-network-secondary-a
      - replicated-log-network-secondary-b

  secondary_a:
    build: secondary_a/
    environment:
      - FLASK_DEBUG=1
      - DELAY=1
    command: python ./secondary.py
    ports:
      - "5001:5001"
    networks:
      - replicated-log-network-secondary-a
    depends_on:
      - master

  secondary_b:
    build: secondary_a/
    environment:
      - FLASK_DEBUG=1
      - DELAY=1
    command: python ./secondary.py
    ports:
      - "5002:5001"
    networks:
      - replicated-log-network-secondary-b
    depends_on:
      - master

networks:
  replicated-log-network-secondary-a:
    driver: bridge
  replicated-log-network-secondary-b:
    driver: bridge